---
- hosts: rpi
  gather_facts: false
  vars:
    cadvisor_version: 0.45.0
  tasks:
    - name: download cadvisor binary
      ansible.builtin.get_url:
        url: https://github.com/google/cadvisor/releases/download/v{{ cadvisor_version }}/cadvisor-v{{ cadvisor_version }}-linux-arm
        dest: /usr/local/bin/cadvisor
        owner: root
        group: root
        mode: 755
      register: download_binary
      become: true
    
    - name: ensure systemd service unit
      ansible.builtin.template:
        src: cadvisor.service.j2
        dest: /etc/systemd/system/cadvisor.service
        owner: root
        group: root
        mode: 0644
      register: systemd_service
      become: true

    - name: ensure systemd service is enabled and started
      ansible.builtin.systemd:
        name: cadvisor
        enabled: true
        state: started
      become: true

    - name: reload systemd daemon and restart cadvisor if service changed
      ansible.builtin.systemd:
        name: cadvisor
        state: restarted
        daemon_reload: true
      when: systemd_service.changed
      become: true