---
- hosts: rpi
  gather_facts: false
  vars:
    node_exporter_version: 1.5.0
    collectors:
      - conntrack
      - cpu
      - diskstats
      - edac
      - filesystem
      - loadavg
      - meminfo
      - netdev
      - thermal_zone
      - udp_queues
      - uname
      - stat
  tasks:
    - name: download node exporter binary
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-armv6.tar.gz
        extra_opts:
          - --strip-components=1
        include:
          - node_exporter-{{ node_exporter_version }}.linux-armv6/node_exporter
        dest: /usr/local/bin
        owner: root
        group: root
        remote_src: true
      register: download_binary
      become: true
    
    - name: ensure systemd service unit
      ansible.builtin.template:
        src: node-exporter.service.j2
        dest: /etc/systemd/system/node-exporter.service
        owner: root
        group: root
        mode: 0644
      register: systemd_service
      become: true

    - name: ensure systemd service is enabled and started
      ansible.builtin.systemd:
        name: node-exporter
        enabled: true
        state: started
      become: true

    - name: reload systemd daemon and restart node-exporter if service changed
      ansible.builtin.systemd:
        name: node-exporter
        state: restarted
        daemon_reload: true
      when: systemd_service.changed
      become: true